rules:
  CallbackFuzz:
    description: Test for open redirects and potential SSRFs by checking for certain responses or callbacks to your server
    extraParams:
      - "url"
      - "redirectUri"
    injections:
      - "http://[[domain]].example.net/"
      - "//example.net?targetUrl=[[fullurl]]"
      - "https://example.net?target=[[domain]][[path]]"
    expectation:
      responseContents:
        - Example Domain

  SqlInjectionCheck:
    description: Test for potential SQL injections by injecting characters to break SQL statements
    injections:
      - "'"
      - )
    expectation:
      responseCodes:
        - 500
    heuristics:
      injection: "''"
      baselineMatches:
        - "responseCode"

  XssDetection:
    description: Test for XSS by discovering potentially unsanitized/encoded input in responses
    extraParams:
      - "param"
    injections:
      - '"><h2>asd</h2>'
    expectation:
      responseContents:
        - '<h2>asd</h2>'
      responseHeaders:
        Content-Type: html

slack:
  channel: "#channel-name"
  botToken: "MY-BOT-TOKEN"
